### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by dbermond** [uavs3/uavs3e#19]
I'm getting the following build error:

```
[100%] Linking C executable uavs3enc
/usr/bin/ld: src/libuavs3e.so: undefined reference to `min'
/usr/bin/ld: src/libuavs3e.so: undefined reference to `max'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/uavs3enc.dir/build.make:104: uavs3enc] Error 1
make[2]: Leaving directory '/build/uavs3e-git/src/uavs3e/build/linux'
make[1]: *** [CMakeFiles/Makefile2:115: CMakeFiles/uavs3enc.dir/all] Error 2
make[1]: Leaving directory '/build/uavs3e-git/src/uavs3e/build/linux'
make: *** [Makefile:149: all] Error 2
make: Leaving directory '/build/uavs3e-git/src/uavs3e/build/linux'
```

A git bisect shows that is caused by commit 218528c36d942b87021e0235e9e8b11bddd209fb.

I can confirm that it was building fine until commit 457b5c9fa9e491be63104461c2c5d8908df373f5.

System information:

OS: Arch Linux x86_64
Compiler: gcc 10.2.0
CMake: 3.19.2
glibc: 2.32

**Comment by dbermond** [comment]
I can confirm that this issue was fixed by commit https://github.com/uavs3/uavs3e/commit/2af374fc682c0cd869c5f141a481e2c243b275d3.

Thank you for fixing this. Closing.
